---
version: '3'
#version: '2.4'

services:
    app:
        build: app
        restart: always
        volumes:
           - host_efs:/mydata

#        volumes:
#          - type: volume
#            source: /home/ec2-user/efs
#            target: /mydata
#            volume:
#              nocopy: true

    proxy:
        build: proxy
        restart: always
        ports:
         - "8080:8080"

volumes:
  host_efs:
    driver: local
    driver_opts:
      type: none
      device: /home/ec2-user/efs
      o: bind
